spring:
  application:
    name: Task Test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:taskdb;create=true
    data: classpath:tasks.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
  h2.console:
    enabled: true
    settings.web-allow-others: true